[project]
title = "Gym Data Analysis"
version = "0.1.0"
port = 8501
slug = "gym-data-analysis"  
entrypoint = "script.py"    

[branding]
name = "Gym Data Analysis"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.gym_data]
type="csv"
path = "data/megaGymDataset.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"